server:
  port: 8080
spring:
  redis:
    host: 47.103.110.39
    port: 6379
    password: Xhf199606

    # Lettuce连接池介绍(添加连接池)
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

    client-type: lettuce

